server:
  port: 80

mybatis:
  # mybatis配置文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml
  # 所有Model别名类所在包
  type-aliases-package: com.szlaun.launtech.*.*.dto
  # mapper映射文件
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库名称
#    url: jdbc:mysql://192.168.3.103:3306/launtech?serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/sap_test?serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-total: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 150